#!/bin/bash
sudo apt-get update && sudo apt-get install -y -qq --no-install-recommends wget unzip python openssh-client python-openssl && sudo apt-get clean
wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip && unzip google-cloud-sdk.zip && rm google-cloud-sdk.zip
google-cloud-sdk/install.sh --usage-reporting=true --path-update=true --bash-completion=true --rc-path=/.bashrc --disable-installation-options

gcloud --quiet components update pkg-go pkg-python pkg-java preview alpha beta app kubectl
gcloud --quiet config set component_manager/disable_update_check true

gcloud config set project $SENTIA_PROJECT
gcloud config set compute/zone $SENTIA_ZONE
gcloud config set container/cluster $SENTIA_CLUSTER

echo $GCLOUD_KEY >> gcloud.json
# echo $GCLOUD_PRIVATE_KEY >> $HOME/.ssh/google_compute_engine
# echo $GCLOUD_PUBLIC_KEY >> $HOME/.ssh/google_compute_engine.pub
# sudo chmod 600 $HOME/.ssh/google_compute_engine
# sudo chmod 600 $HOME/.ssh/google_compute_engine.pub
gcloud -q auth activate-service-account --key-file gcloud.json
yes | gcloud -q compute config-ssh
