#!/usr/bin/env node
var WebSocket = require('ws');
var SERVICE_ID = process.env.TUTUM_SERVICE_ID;
var userPublicToken = process.env.TUTUM_PUBLIC_TOKEN;
var username =  process.env.TUTUM_USER;

var ws = new WebSocket('wss://stream.tutum.co/v1/events?token='+ userPublicToken +'&user=' +username);

ws.on('open', function() {
    console.log('Connected');
});

ws.on('error', function(message) {
    console.log('Error: %s', message);
    process.exit(1);
});

ws.on('message', function(message) {
  var data = JSON.parse(message);
  if (data.type !== 'service') {
    return;
  }
  if (data.resource_uri !== `/api/v1/service/${SERVICE_ID}/`) {
    return;
  }
  console.log(data.state);
  if (data.state === 'Running') {
    process.exit(0);
  }


});

ws.on('close', function() {
    console.log('Socket closed', arguments);
    process.exit(1);
});
